name: Documentation
on:
  push:
    branches:
      - develop
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme
          
      - name: Build documentation
        run: |
          cd cordyceps/docs
          make html  # Of gebruik een andere opdracht die nodig is om de documentatie te bouwen
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: cordyceps/docs/_build
          branch: gh-pages
