name: Build Docs

on:
  push:
    branches:
      - main  # Voeg hier eventueel andere branchnamen toe als dat nodig is
      - develop
  pull_request:
    branches:
      - main  # Voeg hier eventueel andere branchnamen toe als dat nodig is
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme
          sudo apt-get install latexmk
          sudo apt-get install texlive-latex-extra
          sudo apt-get install texlive-xetex
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install xindy
          
      - name: Build documentation
        run: |
          cd cordyceps/docs
          make html  # Of gebruik een andere opdracht die nodig is om de documentatie te bouwen
          make latexpdf
          
      - name: Archive html documentation
        uses: actions/upload-artifact@v2
        with:
          name: html documentation
          path: cordyceps/docs/_build/html  # Het pad naar de gegenereerde HTML-documentatie
          
      - name: Archive latex documentation
        uses: actions/upload-artifact@v2
        with:
          name: latex documentation
          path: cordyceps/docs/_build/latex  # Het pad naar de gegenereerde latex-documentatie
          
  retrieve-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: html-documentation

      - name: Extract artifact
        run: |
          mkdir extracted-artifact
          unzip ${{ github.workspace }}/html-documentation -d extracted-artifact

      - name: Move artifact to gh-pages branch
        run: |
          git checkout -b gh-pages
          cp -R extracted-artifact/* .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update gh-pages with artifact"
          git push
